name: map_pin_picker
description: A Flutter package for creating pin in map center and animate it with map movement so the user can select his location  .
version: 0.0.1

homepage: https://www.pharous.com/
repository: https://github.com/pharous-flutter/map_pin_picker
issue_tracker: https://github.com/pharous-flutter/map_pin_picker/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
